
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef WIN32TEST_H
#define WIN32TEST_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 qnxtest_valueRangeTest (UNS8 typeValue, void * value);
const indextable * qnxtest_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data qnxtest_Data;

#endif // qnxTEST_H
